#!/usr/bin/env python3
import logging
import signal
import threading
import time
from datetime import datetime

import config
from mqtt_service import MQTTService
from plc_modbus import PLCModbus
from scanner import QRScanner
from session_store import SessionStore
from ticket_printer import TicketPrinter

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
log = logging.getLogger("gate-in")


def iso_now():
    # Project format: yyyy-MM-dd'T'HH:mm:ss.SSS
    return datetime.now().strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3]


class GateInApp:
    def __init__(self):
        self.stop_event = threading.Event()

        self.plc = PLCModbus()
        self.mqtt = MQTTService()
        self.printer = TicketPrinter()
        self.sessions = SessionStore()

        self.scanner = QRScanner(self.on_qr)

        self.state_lock = threading.Lock()
        self.vehicle_present = False
        self.session_active = False
        self.session_started_at = 0.0

        self.last_inputs = None
        self.last_outputs = None

        self.last_s1 = False
        self.last_s2 = False
        self.last_s3 = False
        self.last_s4 = False

        self.last_event_time = {
            "S1": 0.0,
            "S2": 0.0,
            "S3": 0.0,
            "S4": 0.0,
        }

    # ---------------- lifecycle ----------------

    def start(self):
        log.info("Starting Gate IN BBB application")

        self.mqtt.connect()

        if not self.plc.connect():
            raise RuntimeError("PLC Modbus connection failed")

        self.scanner.start()

        # Main PLC polling loop.
        self.run()

    def stop(self):
        if self.stop_event.is_set():
            return

        self.stop_event.set()
        self.scanner.stop()
        self.mqtt.disconnect()
        self.plc.close()
        log.info("Gate IN application stopped")

    # ---------------- PLC polling ----------------

    def run(self):
        while not self.stop_event.is_set():
            inputs = self.plc.read_inputs()
            if inputs is None:
                time.sleep(1)
                continue

            outputs = self.plc.read_outputs_and_bits()

            self.last_inputs = inputs
            self.last_outputs = outputs

            self.process_input_edges(inputs)

            # Keep B21 strictly as a trigger generated by BBB.
            # Rung 33 in PLC automatically unlatches it.
            #
            # We do not write R1/R2 from BBB.

            self.check_session_timeout()

            time.sleep(config.PLC_POLL_INTERVAL)

    def process_input_edges(self, x):
        now = time.monotonic()

        s1 = x["S1"]
        s2 = x["S2"]
        s3 = x["S3"]
        s4 = x["S4"]

        # S4 rising edge = vehicle detected at dispenser.
        if s4 and not self.last_s4:
            self.on_vehicle_detected()

        # S1 rising edge = motorcycle.
        if s1 and not self.last_s1:
            self.on_vehicle_choice("motorcycle")

        # S2 rising edge = car.
        if s2 and not self.last_s2:
            self.on_vehicle_choice("car")

        # S3 is physically NC in your project.
        # The logical value must be verified in Outseal Online Monitor.
        # Here we treat a logical rising edge as "help event".
        if s3 and not self.last_s3:
            self.on_help_request()

        self.last_s1 = s1
        self.last_s2 = s2
        self.last_s3 = s3
        self.last_s4 = s4

    # ---------------- vehicle/session ----------------

    def on_vehicle_detected(self):
        with self.state_lock:
            if self.session_active:
                log.warning("S4 detected while previous session is active")
                return

            self.vehicle_present = True
            self.session_active = True
            self.session_started_at = time.monotonic()

        log.info("Vehicle detected at dispenser (S4)")

    def on_vehicle_choice(self, vehicle_type):
        with self.state_lock:
            if not self.session_active:
                log.warning(
                    "Vehicle choice %s ignored: no active S4 session",
                    vehicle_type,
                )
                return

        # Debounce.
        if not self.debounced(vehicle_type):
            return

        threading.Thread(
            target=self.handle_general_visitor,
            args=(vehicle_type,),
            name=f"general-{vehicle_type}",
            daemon=True,
        ).start()

    def on_qr(self, member_code):
        with self.state_lock:
            if not self.session_active:
                log.warning("QR ignored: no active vehicle session")
                return

        threading.Thread(
            target=self.handle_member,
            args=(member_code.strip(),),
            name="member-handler",
            daemon=True,
        ).start()

    def handle_general_visitor(self, vehicle_type):
        session_number = self.sessions.next_session()
        entry_time = iso_now()

        log.info(
            "General visitor: session=%s vehicle=%s entry=%s",
            session_number,
            vehicle_type,
            entry_time,
        )

        try:
            # Server must receive the data before opening the gate.
            self.mqtt.publish_general(
                session_number,
                vehicle_type,
                entry_time,
            )

            # Print before opening the gate. Any printer exception is treated
            # as a help condition; the gate is NOT opened.
            try:
                self.printer.print_ticket(
                    session_number,
                    vehicle_type,
                    entry_time,
                )
            except Exception as exc:
                log.exception("Printer error / possible paper-out: %s", exc)
                self.publish_help(config.HELP_REASON_PRINTER)
                return

            # BBB writes only B21. PLC decides whether R1 can actually turn ON.
            if not self.plc.open_request():
                raise RuntimeError("Could not send B21 OPEN_REQUEST")

            if self.plc.wait_gate_open(timeout=5):
                log.info("Barrier OPEN command detected (R1)")
            else:
                log.warning("B21 sent but R1 was not observed within 5s")

        except Exception:
            log.exception(
                "General visitor transaction failed; gate will NOT be opened"
            )

        finally:
            self.finish_transaction_state()

    def handle_member(self, member_code):
        if not member_code:
            log.warning("Empty member code")
            return

        session_number = self.sessions.next_session()
        entry_time = iso_now()

        log.info(
            "Member scan: session=%s member=%s entry=%s",
            session_number,
            member_code,
            entry_time,
        )

        try:
            verified, response = self.mqtt.verify_member(
                session_number,
                member_code,
                entry_time,
            )

            if not verified:
                log.warning(
                    "Member NOT VERIFIED: %s. Barrier remains closed.",
                    member_code,
                )
                return

            # Verified member: open gate through PLC handshake.
            if not self.plc.open_request():
                raise RuntimeError("Could not send B21 OPEN_REQUEST")

            if self.plc.wait_gate_open(timeout=5):
                log.info("Verified member barrier OPEN (R1)")
            else:
                log.warning("B21 sent but R1 was not observed within 5s")

        except TimeoutError:
            log.error(
                "Member verification timeout. Barrier remains closed."
            )
        except Exception:
            log.exception(
                "Member transaction failed; gate will NOT be opened"
            )
        finally:
            self.finish_transaction_state()

    def on_help_request(self):
        if not self.debounced("S3"):
            return

        self.publish_help(config.HELP_REASON_BUTTON)

    def publish_help(self, reason):
        timestamp = iso_now()
        try:
            self.mqtt.publish_help(timestamp, reason)
        except Exception:
            log.exception("Failed publishing help request: %s", reason)


    def finish_transaction_state(self):
        with self.state_lock:
            self.session_active = False
            self.vehicle_present = False
            self.session_started_at = 0.0

    def check_session_timeout(self):
        with self.state_lock:
            active = self.session_active
            started = self.session_started_at

        if active and started:
            if time.monotonic() - started > config.USER_ACTION_TIMEOUT:
                log.warning(
                    "Vehicle interaction timeout. Resetting BBB session state."
                )
                self.finish_transaction_state()

    def debounced(self, key):
        now = time.monotonic()
        last = self.last_event_time.get(key, 0.0)

        if now - last < config.EVENT_DEBOUNCE:
            return False

        self.last_event_time[key] = now
        return True


app = GateInApp()


def shutdown_handler(signum, frame):
    log.info("Signal %s received", signum)
    app.stop()


if __name__ == "__main__":
    signal.signal(signal.SIGINT, shutdown_handler)
    signal.signal(signal.SIGTERM, shutdown_handler)

    try:
        app.start()
    except KeyboardInterrupt:
        pass
    except Exception:
        log.exception("Fatal application error")
        raise
    finally:
        app.stop()
